app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, ValidationError, Email, EqualTo
from app.model import UserModel


class LoginForm(FlaskForm):
    """Accepts a nickname and a room."""
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = UserModel.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        user = UserModel.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')

app/__init__.py
from flask import Flask, session
from flask_socketio import SocketIO
from flask_session import Session
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import os

socketio = SocketIO()
login = LoginManager()
db = SQLAlchemy()
migrate = Migrate()
session = Session()

basedir = os.path.abspath(os.path.dirname(__file__))

SQLALCHEMY_TRACK_MODIFICATIONS = False
SESSION_TYPE = 'redis'


def create_app(debug=False):
    """Create an application."""
    # app = Flask(__name__)
    app = Flask(__name__, static_url_path="/static", static_folder="static")
    app.debug = debug
    app.config['SECRET_KEY'] = 'thisIsASecretKey#1209'
    app.config['SESSION_TYPE'] = 'filesystem'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL') or \
        'sqlite:///' + os.path.join(basedir, 'app.db')
    #app.config['SESSION_TYPE'] = 'sqlalchemy'
    #app.config['SESSION_SQLALCHEMY_TABLE'] = 'sessions'
    #app.config['SESSION_SQLALCHEMY'] = db

    # register blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    # end blueprint

    # init socket io app
    socketio.init_app(app, manage_session=False)
    # end socket io app init

    # start flask-session
    session.init_app(app)
    # end flask session

    # start flask-login init
    login.init_app(app)
    login.login_view = 'main.loginFunc'
    # end flask login

    # start flask-sqlalchemy
    db.init_app(app)
    # end flask-sqlalchemy

    # start flask-migrate
    migrate.init_app(app, db)
    # end flask-migrate

    # import models from model.py
    from app import model
    # done with import

    # session.app.session_interface.db.create_all()

    # pass back app
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

app/main/routes.py
from flask import session, redirect, url_for, render_template, request, session, jsonify, flash, redirect
from flask_login import current_user, login_user, logout_user, login_required
from flask_session import sessions
from . import main
from .. import login
from .forms import LoginForm, RegistrationForm
from app.model import UserModel
from app import db


@main.route('/room/<roomNumber>')
def joinRoom(roomNumber):
    pass


@main.route('/index')
@login_required
def index():
    session['isPrivate'] = False
    return render_template('mainChat.html')


@main.route('/', methods=['GET', 'POST'])
@main.route('/login', methods=['GET', 'POST'])
def loginFunc():
    session['isPrivate'] = False
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = UserModel.query.filter_by(username=form.username.data).first()
        print(f'Current User is {user}')
        if user is None or not user.check_password(form.password.data):
            flash("Invalid username or password")
            return redirect(url_for('main.loginFunc'))
        login_user(user, remember=form.remember_me.data)

        return redirect(url_for('main.index'))
    return render_template('login.html', title='Sign In', form=form)


@main.route('/logout', methods=['POST'])
def logout():
    logout_user()
    return redirect(url_for('main.loginFunc'))
##---------------------SESSION MANAGEMENT---------------------##


@main.route('/session', methods=['GET', 'POST'])
def session_access():
    if request.method == 'GET':
        val = jsonify({
            'session': session.get('value', ''),
            'user': current_user.id,
            'userName': UserModel.query.filter_by(id=current_user.id).first().username
            if current_user.is_authenticated else 'anonymous'
        })
        print(f'Session value is {val}')
        return val
    data = request.get_json()
    print(data)
    if 'session' in data:
        session['value'] = data['session']
    elif 'user' in data:
        if data['user']:
            login_user(UserModel(data['user']))
        else:
            logout_user()
    return '', 204


@main.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = UserModel(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        print(f'Current user id is {user.id}')
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('main.loginFunc'))
    return render_template('register.html', title='Register', form=form)


@login_required
@main.route('/user/<name>')
def getUser(name):
    userDat = UserModel.query.filter_by(username=name).first()
    if userDat == None:
        return render_template('errorPage.html', type_of_error="404 Not Found", message=f'{name} was not found')
    return render_template('UserPage.html', messages=userDat.messages.all(), user=userDat)


@login_required
@main.route('/private')
def createRoom():
    return render_template('join_room.html')


@login_required
@main.route('/private/<room>')
def getRooms(room):
    session['isPrivate'] = True
    return render_template('privateChat.html', room=room)

app/templates/UserPage.html
{% extends "index.html" %}
{% block content %}
<div style="display: grid;justify-items: center;overflow: hidden; grid-template-columns: 25% 75%; margin-top: 30px;">
    <div id="userInfo" style="display: grid;
    grid-template-rows: auto 80px 80px;">
        {% if not user.userImage %}
        <img style="width: 100%;" src="https://raw.githubusercontent.com/AHarmlessPyro/chatApp/master/static/egg.jpg">
        {% else %} <img style="width: 100%;" src="{{message['image']}}">
        {% endif %}
        <div>
            {{user.username}}
        </div>
        <div>
            {{user.email}}
        </div>
    </div>
    <div id="messageList" style="display: grid; grid-template-columns:33% 1% 66%; width: 100%; padding: 30px;">
        {% for message in messages%}
        <div style=" justify-self: flex-start;">{{message.timestamp}}</div>
        :
        <div style="justify-self:flex-start;">{{message.body}} </div>

        {% endfor %}
    </div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
{% endblock %}

<!--
    <div id="messages">
    </div>
    <div id="messageField">
        <textarea id="textArea" placeholder="Messages Go Here"></textarea>
        <button id="openGIFPanel" onclick="openGIFPanel()" style="margin: 5%;
        background-color: transparent;
        border-color: rgba(255,255,255,0.5);">GIF</button>
    </div>
</div>

<div style="width: calc(100vw - 45px);
background-color: rgba(100,100,100,0.95);
max-height: calc(90vh + 11px);
display: grid;
visibility: hidden;
grid-template-rows: 75px auto;
margin-top: 2vh;
position: absolute;
top: 36px;
transition: opacity 1s;
opacity: 0.0;" id="gifPanel">
    <div style="
    /* font-size: 30px; */
    display: grid;
    margin: 20px;
    grid-template-columns: 90% auto;
    /* column-gap: 10px; */
    max-height: 35px;
    ">
        <div>
            <input id="gif" style="display: grid;
            width: 100%;
            font-size: 15px;
            height: 100%;">
        </div>
        <div style="cursor: pointer; justify-self: flex-end; font-size: 23px;" onclick="closeGifPanel()">
            &#10005;
        </div>
    </div>
    <div style="
        padding: 10px;
        display: grid;
        grid-template-columns: 23.75% 23.75% 23.75% 23.75%;
        column-gap: 3.333%;
        row-gap: 10px;
        height: calc(90vh - 75px);" id="appendGif">
    </div>
</div>-->

app/templates/errorPage.html
{% extends "index.html" %}

{% block content %}
<h1>{{type_of_error}}</h1>
<h3>{{message}}</h3>

{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Bare - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="{{url_for('static',filename='css/bootstrap.min.css')}}" rel="stylesheet">
  <!-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="#">ChatUp!</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#" onclick="fetch('/login',{method: 'post'}).then(response=>{
              console.log(response);
              window.location.href = response.url;
            })">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="#" onclick="fetch('/logout',{method: 'post'}).then(response=>{
              console.log(response);
              window.location.href = response.url;
            })">Logout</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container-fluid">
    {% block content %}
    {% endblock %}
    <!-- <div class="row">
      <div class="col-lg-12 text-center">
        <h1 class="mt-5">A Bootstrap 4 Starter Template</h1>
        <p class="lead">Complete with pre-defined file paths and responsive navigation!</p>
        <ul class="list-unstyled">
          <li>Bootstrap 4.3.1</li>
          <li>jQuery 3.4.1</li>
        </ul>
      </div>
    </div> -->
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="{{url_for('static',filename='js/jquery.slim.min.js')}}"></script>
  <script src="{{url_for('static',filename='js/bootstrap.bundle.min.js')}}"></script>

</body>

</html>

app/templates/item.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Flask SocketIO Test</title>
</head>

<body style="display: grid;justify-items: center;overflow: hidden;">
    <style>
        .textBox {
            max-width: max-content;
            border: 2px solid black;
            border-radius: 40px;
            padding: 0em 1em;
            margin: 10px 0px;
            padding-top: 4px;
        }

        #messages {
            border: 2px solid;
            border-radius: 20px;
            min-width: 90vw;
            max-width: 90vw;
            min-height: 85vh;
            max-height: 85vh;
            margin: 1vw 2vh;
            padding: 1vw;
            display: grid;
            grid-template-rows: repeat(auto-fit, minmax(50px, max-content));
            overflow-y: scroll;
            overflow: -moz-scrollbars-none;
            scrollbar-width: none;
        }

        #messages::-webkit-scrollbar {
            width: 0px;
            ;
        }

        #messageField {
            min-width: 90vw;
            border: 2px solid black;
            border-radius: 20px;
            min-height: 2vw;
        }
    </style>
    <div id="messages">
    </div>
    <!-- <input type="text" id="messageField"> -->
    <textarea id="messageField"></textarea>
    <!-- <p>Some sample code to make sure Flask-SocketIO works...</p>
    <button onclick="createGame()">Create Game</button>
    <p>Some sample code to make sure Create Rooms...</p>
    <button onclick="createRooms()">Create Room</button>
    <p>Some sample code to make sure get rooms...</p>
    <button onclick="createGame()">Get rooms</button>
    -->
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
    <script type="text/javascript" charset="utf-8">

        var sender = (Math.random() * 100000).toString(16);
        console.log("Sender is " + sender);

        document.getElementById('messageField').addEventListener('keydown', (event) => {
            //console.log(event);
            if (event.key == "Enter" && !(event.shiftKey || event.ctrlKey || event.altKey)) {
                socket.emit('messagePublic', { message: document.getElementById('messageField').value, sender: sender })
            }
        })

        var socket = io({ transports: ['websocket'] });
        socket.connect('http://' + document.domain + ':' + location.port);
        // verify our websocket connection is established
        socket.on('connect', function () {
            console.log('Websocket connected!');
        });

        // message handler for the 'join_room' channel
        socket.on('hello', function (msg) {
            console.log(msg);
        });

        socket.on('NewRoom', function (msg) {
            console.log(msg);
        })
        // createGame onclick - emit a message on the 'create' channel to 
        // create a new game with default parameters

        socket.on('newMessage', (event) => {
            console.log(event);
            let align_side = "flex-start";
            if (event.sender == sender) {
                console.log("sender was me");
                align_side = "flex-end";
            } else {
                console.log("sender was someone else");
            }

            let actualMessage = event.message.replace(/\n/gm, '<br>');
            document.getElementById('messages').insertAdjacentHTML('beforeend',
                `<div class="textBox" style="justify-self:${align_side};">${actualMessage}</div>`
            );
        })

        function createGame() {
            console.log('Creating game...');
            socket.emit('create', { size: 'normal', teams: 2, dictionary: 'Simple' });
        }

        function getRooms() {

        }

        function createRooms() {
            console.log("Creating rooms");
            socket.emit('createRoom')
        }

        socket.on('connected', event => conn_disconn(event))
        socket.on('disconnected', event => conn_disconn(event))
        function conn_disconn(event) {
            console.log(event);
        }
    </script>
</body>

</html>

app/templates/join_room.html
{% extends "index.html" %}
{% block content %}

<div style="display: grid; justify-content: center;">
    <div>
        <h2>
            Create Room?
        </h2>
    </div>
    <div>
        <input id="room_name" placeholder="Room Name">
    </div>
    <div>
        <input id="username" placeholder="Username of other person">
    </div>
    <button onclick="createRoom()"> Create ROOM?</button>
    <div>
        <h2>
            Join Room?
        </h2>
    </div>
    <div>
        <input id="room_name_join" placeholder="Room Name">
    </div>
    <button onclick="joinRoom()"> Join ROOM?</button>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
<script>

    var socket;
    var sender;
    var sender_id;
    var messageCount = 0;

    fetch('/session').then(
        response => {
            console.log(response);
            response.json().then(json => {
                console.log(json);
                const jsonDat = json;
                sender = json.userName;//(Math.random() * 100000).toString(16);
                sender_id = json.user;
                console.log("Sender is " + sender);

                // Create socket-io object with websocket transport enforced
                socket = io();//{ transports: ['polling'] }//{ transports: ['websocket'] }

                events();

                // Connect to socket at a location
                socket.connect('http://' + document.domain + ':' + location.port, { 'isPrivate': true });
            })
        }
    );

    function createRoom() {
        socket.emit('create_room', { 'room': document.getElementById('room_name').value, 'username': document.getElementById('username').value })
    }

    function joinRoom() {
        socket.emit('join_room', { 'room': document.getElementById('room_name_join').value })
    }

    function events() {
        // Socket message Events
        socket.on('connect', function () {
            sendMessage(`${sender} Joined the lobby`, "System", -1);
        });

        socket.on('join_room', () => {
            window.location.href = `private/${document.getElementById('room_name').value || document.getElementById('room_name_join').value}`
        })

        socket.on('not_available', () => {
            alert("Room is occupied or not created. Please select a different room")
        })
    }

    function sendMessage(message, send_source = sender, send_id = sender_id) {
        socket.emit('messagePublic', { message: message, sender: send_source, id: send_id });
    }

</script>

{% endblock %}

app/templates/login.html
{% extends "index.html" %}
{% block content %}
<div id="LoginElement">
    <style>
        :root {
            --mainBackground: var(--white);
            --sideBackground:
                /*var(--gray-dark)*/
                var(--dangar);
            --errorTextColor: var(--danger);
        }

        .arrow_box {
            position: relative;
            background: var(--mainBackground);
            border: 4px solid var(--sideBackground);
            padding: 3px;
            margin-left: 30px;
        }

        .arrow_box:after,
        .arrow_box:before {
            right: 100%;
            top: 50%;
            border: solid transparent;
            content: " ";
            height: 0;
            width: 0;
            position: absolute;
            pointer-events: none;
        }

        .arrow_box:after {
            border-color: rgba(136, 183, 213, 0);
            border-right-color: var(--mainBackground);
            border-width: 10px;
            margin-top: -10px;
        }

        .arrow_box:before {
            border-color: rgba(194, 225, 245, 0);
            border-right-color: var(--sideBackground);
            border-width: 15px;
            margin-top: -15px;
        }
    </style>
    <h1>Sign In</h1>
    <hr>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    <div style="display: grid; justify-content: center;">
        <form action="" method="post" novalidate>
            {{ form.hidden_tag() }}
            <p>
                {{ form.username.label }}<br>
                {{ form.username(size=32) }}
                {% for error in form.username.errors %}
                <span style="color: var(--errorTextColor);" class="arrow_box">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.password.label }}<br>
                {{ form.password(size=32) }}
                {% for error in form.password.errors %}
                <span style="color: var(--errorTextColor);" class="arrow_box">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
            <p> {{ form.submit(style="width:100%") }} </p>
        </form>
        <a href="{{url_for('main.register')}}">
            <button onclick="location.href = `{{url_for('main.register')}}`" style="width: 100%;">Register New
                User? </button>
        </a>
    </div>
</div>
{% endblock %}

app/templates/register.html
{% extends "index.html" %}

{% block content %}
<h1>Register</h1>
<div style="display: grid; justify-content: center;">
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
</div>
{% endblock %}